global:
  scrape_interval: 15s  # By default, scrape targets every 15 seconds.

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  - job_name: 'prometheus'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
      - role: pod

  - job_name: 'kubernetes-services'
    kubernetes_sd_configs:
      - role: service

  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
      - role: node
