apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 5775
          protocol: UDP
        - containerPort: 6831
          protocol: UDP
        - containerPort: 6832
          protocol: UDP
        - containerPort: 5778
        - containerPort: 16686
        - containerPort: 14268
        - containerPort: 9411
        env:
          - name: COLLECTOR_ZIPKIN_HTTP_PORT
            value: "9411"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
spec:
  ports:
  - name: query
    port: 16686
    protocol: TCP
    targetPort: 16686
  - name: collector
    port: 14268
    protocol: TCP
    targetPort: 14268
  selector:
    app: jaeger
  type: NodePort
